[mcp]
sse_servers = [ ]
shttp_servers = [ ]

  [[mcp.stdio_servers]]
  name = "context7"
  command = "npx"
  args = [ "-y", "@upstash/context7-mcp@latest" ]

  [[mcp.stdio_servers]]
  name = "flymcp"
  command = "/Users/vinh.nguyenxuan/flymcp/flymcp"
  args = [ ]
  env = { }

  [[mcp.stdio_servers]]
  name = "fetch"
  command = "uvx"
  args = [ "mcp-server-fetch" ]
  env = { }
