# Development fly.toml
app = 'vtchat-dev'
primary_region = 'sin'

[build]

[env]
  NODE_ENV = 'development'
  BASE_URL = 'https://vtchat-dev.fly.dev'
  BETTER_AUTH_URL = 'https://vtchat-dev.fly.dev'
  NEXT_PUBLIC_BASE_URL = 'https://vtchat-dev.fly.dev'
  NEXT_PUBLIC_APP_URL = 'https://vtchat-dev.fly.dev'
  NEXT_PUBLIC_COMMON_URL = 'https://vtchat-dev.fly.dev'
  NEXT_PUBLIC_BETTER_AUTH_URL = 'https://vtchat-dev.fly.dev'
  CREEM_ENVIRONMENT = 'sandbox'
  BETTER_AUTH_ENV = 'development'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
  grace_period = "15s"
  interval = "60s"
  method = "GET"
  timeout = "10s"
  path = "/api/health"

[[http_service.checks]]
  type = "tcp"
  grace_period = "5s"
  interval = "15s"
  timeout = "2s"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
