# Production fly.toml
app = 'vtchat'
primary_region = 'sin'

# Global 3-region setup for optimal coverage
# sin: Asia-Pacific (primary)
# iad: USA (Ashburn, Virginia) 
# ams: Europe (Amsterdam, Netherlands)

[build]

[env]
  NODE_ENV = 'production'
  BASE_URL = 'https://vtchat.io.vn'
  BETTER_AUTH_URL = 'https://vtchat.io.vn'
  NEXT_PUBLIC_BASE_URL = 'https://vtchat.io.vn'
  NEXT_PUBLIC_APP_URL = 'https://vtchat.io.vn'
  NEXT_PUBLIC_COMMON_URL = 'https://vtchat.io.vn'
  NEXT_PUBLIC_BETTER_AUTH_URL = 'https://vtchat.io.vn'
  CREEM_ENVIRONMENT = 'production'
  BETTER_AUTH_ENV = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "15s"
  interval = "30s"
  method = "GET"
  timeout = "10s"
  path = "/api/health"

[[http_service.checks]]
  type = "tcp"
  grace_period = "5s"
  interval = "15s"
  timeout = "2s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1