# Development fly.toml
app = 'vtchat-dev'
primary_region = 'sin'

[build]

[env]
  NODE_ENV = 'development'
  BASE_URL = 'https://vtchat-dev.fly.dev'
  BETTER_AUTH_URL = 'https://vtchat-dev.fly.dev'
  NEXT_PUBLIC_BASE_URL = 'https://vtchat-dev.fly.dev'
  NEXT_PUBLIC_APP_URL = 'https://vtchat-dev.fly.dev'
  NEXT_PUBLIC_COMMON_URL = 'https://vtchat-dev.fly.dev'
  NEXT_PUBLIC_BETTER_AUTH_URL = 'https://vtchat-dev.fly.dev'
  CREEM_ENVIRONMENT = 'sandbox'
  BETTER_AUTH_ENV = 'development'
  PRODUCT_NAME = 'VT Chat Dev'
  PRODUCT_DESCRIPTION = 'AI-powered chat application - Development'
  PRICING_CURRENCY = 'USD'
  PRICING_INTERVAL = 'month'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "60s"
  method = "GET"
  timeout = "5s"
  path = "/api/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
