# fly.toml app configuration file generated for vtchat-dev on 2025-06-26T21:49:22+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'vtchat-dev'
primary_region = 'sin'

[build]
  # Use Dockerfile in root directory (default)
  # dockerfile = "Dockerfile"
  
  # Build arguments (optional)
  # [build.args]
  #   NODE_ENV = "production"

[env]
  BASE_URL = 'https://vtchat-dev.fly.dev'
  BETTER_AUTH_URL = 'https://vtchat-dev.fly.dev'
  NEXT_PUBLIC_BASE_URL = 'https://vtchat-dev.fly.dev'
  NEXT_PUBLIC_APP_URL = 'https://vtchat-dev.fly.dev'
  NEXT_PUBLIC_COMMON_URL = 'https://vtchat-dev.fly.dev'
  NEXT_PUBLIC_BETTER_AUTH_URL = 'https://vtchat-dev.fly.dev'
  CREEM_ENVIRONMENT = 'sandbox'
  BETTER_AUTH_ENV = 'production'
  PRODUCT_NAME = 'VT Chat'
  PRODUCT_DESCRIPTION = 'AI-powered chat application'
  PRICING_CURRENCY = 'USD'
  PRICING_INTERVAL = 'month'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
