[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[environments.development]
[environments.development.deploy]
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"

[environments.production]
[environments.production.deploy]
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"