[package]
name = "vtcode-terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = { version = "0.28", default-features = false, features = ["crossterm"] }
crossterm = "0.28"
anyhow = "1.0"
