export const MATH_TOOL_NAMES = [
    'add',
    'subtract',
    'multiply',
    'divide',
    'exponentiate',
    'factorial',
    'isPrime',
    'squareRoot',
    'sin',
    'cos',
    'tan',
    'sqrt',
    'log',
    'exp',
    'evaluateExpression',
    'abs',
    'floor',
    'ceil',
    'round',
    'min',
    'max',
    'getConstants',
    'asin',
    'acos',
    'atan',
    'sinh',
    'cosh',
    'tanh',
    'gcd',
    'lcm',
    'permutation',
    'combination',
    'mean',
    'median',
    'standardDeviation',
] as const;

export const isMathTool = (toolName: string | undefined): boolean => {
    return !!toolName && MATH_TOOL_NAMES.includes(toolName as any);
};
